---
- name: Gather information about IP interfaces
  hosts: csr
  gather_facts: no
  connection: network_cli 
  tasks:
    - name: Gather IOS facts
      ios_facts:
      register: ios_facts_result
    - name: Display IP interface information
      debug:
        var: ios_facts_result.ansible_facts.ansible_net_interfaces
