---
- name: Cisco AAA compliance
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Check AAA configuration
    ios_command:
      commands: show running-config | section aaa
    register: aaa_config
  
  - name: Report if AAA is missing
    debug:
      msg: "NON-COMPLIANT: AAA not configured device"
    when: aaa_config.stdout[0] == "no aaa new-model"

    